---

- name: "** rocana ** copy rocana.repo template to /etc/yum.repos.d/"
  template: src=rocana.repo.j2 dest=/etc/yum.repos.d/rocana.repo owner=root group=root mode=0644
  tags: deploy-rocana-repo
  