---


- hosts: rocana-webapp
  gather_facts: yes
  tasks:
    - name: "** rocana-supervisor-prep ** register rocana_rsa.pub key from webapp host"
      shell: "cat /opt/rocana/rocana-{{ rocana_version }}/state/rocana-webapp/keys/rocana_rsa.pub | awk {'print $1,$2'}"
      register: pubkey

    - name: "** rocana-supervisor-prep ** create supervisor.conf and stage for rocana-agent deployment"
      local_action: template src=configs/{{ cluster_name }}/rocana-supervisor/supervisor.conf.j2 dest=configs/{{ cluster_name }}/rocana-agent/supervisor.conf

# install rocana agents.  This should be done after the web application is online so that
# agents can be given proper supervisor configs.  
- hosts: rocana-agents
  gather_facts: yes
  roles: 
    - rocana-agent
    

