---

- name: "** rocana webapp ** copy rocana-webapp commands.d to commands.d directory"
  template: src=configs/{{ cluster_name }}/commands.d/rocana-webapp.j2
            dest=/etc/rocana-ops/commands.d/rocana-webapp
            owner=rocana
            group=rocana
            mode=0644
  tags: rocana-webapp

- name: "** rocana webapp ** copy config template to webapp config directory"
  template: src=configs/{{ cluster_name }}/rocana-webapp/rocana-web.properties.j2
            dest=/etc/rocana-ops/rocana-webapp/rocana-web.properties
            owner=rocana
            group=rocana
            mode=0600
  tags: rocana-webapp

- name: "** rocana webapp ** copy config template to webapp config directory"
  template: src=configs/{{ cluster_name }}/rocana-webapp/{{ item }}.j2
            dest=/etc/rocana-ops/rocana-webapp/{{ item }}
            owner=rocana
            group=rocana
            mode=0644
  with_items:
    - rules-engine-configuration.json
    - action-engine-configuration.json
  tags:
    - rocana-webapp
    - rocana-scheduler

- name: "** rocana webapp ** start and chkconfig service on"
  service: name=rocana-webapp state=started enabled=yes
  tags: rocana-webapp