---

# deploy kerberos krb5.conf to all nodes in the cluster
- name: "** cm-all ** deploy krb5.conf for kerberized cluster support"
  template: src=krb5.conf.j2 dest=/etc/krb5.conf owner=root group=root mode=0644
  when: kerberos_enabled
  tags:
    - enable-kerberos
    - setup-cloudera-agents